### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by LeoniePhiline** [rodgomesc/avell-unofficial-control-center#11]
Follow-up to https://github.com/rodgomesc/avell-unofficial-control-center/issues/8#issuecomment-500142257

Should also help fix #10.

**Comment by LeoniePhiline** [comment]
@rodgomesc Please let me know if you'd like to see anything on the README adjusted before merging.
Thanks!

**Comment by rodgomesc** [comment]
thank you, just folow https://github.com/rodgomesc/avell-unofficial-control-center/pull/12#issuecomment-500166624, and i will merge
