### ISSUE TITLE
Error to install

### ISSUE THREAD

**Issue by henrycmoreira** [rodgomesc/avell-unofficial-control-center#24]
Hello rodgomesc, in my pc have a erro to install "command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6ctkhuga/pyusb" please help to pay a coffe, ajuda ae.

**Comment by rodgomesc** [comment]
Check if this update solver your problem

https://github.com/rodgomesc/avell-unofficial-control-center/pull/23#issuecomment-546328589

**Comment by rodgomesc** [comment]
since this issue had no more feedbacks, I'm closing, if there is any problem let me know
