### ISSUE TITLE
Support for mb-15 G1

### ISSUE THREAD

**Issue by mendelmunkis** [rodgomesc/avell-unofficial-control-center#25]
I have an eluktronics MB-15 (very similar to the G2) with an 8291 keyboard but aucc has one of 3 effects. (Either the light turns off, or it returns to the default blue state,or nothing changes.) What can I do to help add support? I have some coding experience but very limited RE abilities

**Comment by rodgomesc** [comment]
What is the revision of your chip?

**Comment by mendelmunkis** [comment]
Sorry despite looking several times I just noticed it's rev .02

**Comment by rodgomesc** [comment]
in readme have a link for project starbeat, try it
