### ISSUE TITLE
Erro: " import usb.core", ao tentar usar o aplicativo

### ISSUE THREAD

**Issue by brunotix** [rodgomesc/avell-unofficial-control-center#4]
![Screenshot_20190526_021715](https://user-images.githubusercontent.com/3307521/58377676-6df4f680-7f5c-11e9-879e-6ec38785dfcf.png)

**Comment by rodgomesc** [comment]
Hello, can you try install requirements globall, and try again?

Instead of `pip install --user -r requirements.txt`
use `sudo pip install -r requirements.txt`

after try run  again `python main.py -s reactive`

**Comment by rodgomesc** [comment]
You need use `sudo` or login with `root` to run this script

**Comment by brunotix** [comment]
Obrigado! Eu consegui. O que fiz foi usar a referência -H no sudo, ficando assim:

> sudo -H pip3 install -r requirements.txt

> sudo python3 main.py -s reactive

**Comment by rodgomesc** [comment]
Ok i'm closing this issue then
