### ISSUE TITLE
Recoil III (GK5CP6Z) LED Bar control

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [rodgomesc/avell-unofficial-control-center#56]
The PC Specialist recoil III has an LED bar across the front, would it be possible to add controls for this as well?

**Comment by siphomateke** [comment]
@Caffe1neAdd1ct You may be interested in the application I developed for controlling the LED bar on the GK5CP0Z: https://gitlab.com/siphomateke/tongfang-control. It's still very much WIP, but I currently use it to control the LED bar on my personal laptop. avell-unofficial-control-center controls the keyboard's RGB using a USB driver whereas controlling the LED bar requires lower-level ACPI calls, so it's unlikely this repository will be gaining support for the LED bar any time soon.

**Comment by Caffe1neAdd1ct** [comment]
Thanks @siphomateke I'll take a look that the other repo later, it looks great!
