### ISSUE TITLE
ModuleNotFoundError: No module named 'core'

### ISSUE THREAD

**Issue by doulwyi** [rodgomesc/avell-unofficial-control-center#6]
`sudo aucc -c green -b 4
Traceback (most recent call last):
  File "/usr/local/bin/aucc", line 6, in <module>
    from aucc.main import main
  File "/home/bruno/.local/lib/python3.7/site-packages/aucc/main.py", line 11, in <module>
    from core.handler import DeviceHandler
ModuleNotFoundError: No module named 'core'`

**Comment by rodgomesc** [comment]
thanks for the feedback, I believe it was fixed in 122bcea0cc6589c5fc56ce1f1ed1afb1013db3ab,  could uninstall with 

> `sudo pip3 uninstall avel-unofficial-control-center`

 reinstall the project again with 

> `sudo pip3 install avell-unofficial-control-center`

and finally:

> `aucc -c green -b 4`
